In [4]:
import pandas as pd

Creating a Pandas DataFrame using Python Dictionary

In [5]:
x = {"Name": ["Rose", "John", "Jane", "Mary"],\
    "ID":[1, 2, 3, 4], \
    "Department": ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'],\
    "Salary": [100000, 80000, 50000, 6000]}

print(x)

{'Name': ['Rose', 'John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 'Salary': [100000, 80000, 50000, 6000]}

Casting the Dictionary to a DataFrame

In [6]:
df = pd.DataFrame(x)
df

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure    6000

Column Selection
* Note the difference beetween df['ID'] and df[['ID']] , one returns Series and other returns a DataFrame

In [11]:
x = df[['ID']]
x

   ID
0   1
1   2
2   3
3   4

In [12]:
type(x)

pandas.DataFrame

In [13]:
s = df['ID']
type(s)

pandas.Series

Accessing to multiple columns

In [16]:
z = df[['Department', 'Salary', 'ID']]
z

        Department  Salary  ID
0  Architect Group  100000   1
1   Software Group   80000   2
2      Design Team   50000   3
3   Infrastructure    6000   4

### Practice Exercises

Problem 1: Create a dataframe to display the result as below:

In [22]:
dict = {'Student': ['David', 'Samuel', 'Terry', 'Evan'] ,\
        'Age': [27, 24, 22, 32] ,\
        'Country': ['UK', 'Canada', 'China', 'USA'],\
        'Course': ['Python', 'Data Structures', 'Machine Learning', 'Web Development'], \
        'Marks': [85, 72, 89, 76]}

df = pd.DataFrame(dict)
df

  Student  Age Country            Course  Marks
0   David   27      UK            Python     85
1  Samuel   24  Canada   Data Structures     72
2   Terry   22   China  Machine Learning     89
3    Evan   32     USA   Web Development     76

Problem 2: Retrieve the Marks column and assign it to a variable b

In [23]:
b = df[['Marks']]
b

   Marks
0     85
1     72
2     89
3     76

Problem 3: Retrieve the Country and Course columns and assign it to a variable c

In [24]:
select_cols = ['Country', 'Course']
c = df[select_cols]
c

  Country            Course
0      UK            Python
1  Canada   Data Structures
2   China  Machine Learning
3     USA   Web Development

To view the column as a series, just use one bracket:
- Get the Student column as a series Object

In [25]:
x = df['Student']
x

0     David
1    Samuel
2     Terry
3      Evan
Name: Student, dtype: str

In [26]:
type(x)

pandas.Series

Exercise 2: loc() and iloc() functions
loc() is a label-based data selecting method which means that we have to pass the name of the row or column that we want to select. This method includes the last element of the range passed in it.

Simple syntax for your understanding:

loc[row_label, column_label]
iloc() is an indexed-based selecting method which means that we have to pass an integer index in the method to select a specific row/column. This method does not include the last element of the range passed in it.

Simple syntax for your understanding:

iloc[row_index, column_index]
Let us see some examples on the same.¶

In [27]:
df.iloc[0, 0]

'David'

In [28]:
df.iloc[0, 2]

'UK'

In [30]:
df.loc[0, 'Course']

'Python'

In [33]:
df2 = df
df2 = df2.set_index('Student')
df2

         Age Country            Course  Marks
Student
David     27      UK            Python     85
Samuel    24  Canada   Data Structures     72
Terry     22   China  Machine Learning     89
Evan      32     USA   Web Development     76

In [36]:
df2[['Age', 'Country']]

         Age Country
Student
David     27      UK
Samuel    24  Canada
Terry     22   China
Evan      32     USA

In [42]:
df2.loc['David', 'Country']

'UK'

In [41]:
df2.loc['David':'Terry', 'Country']

Student
David         UK
Samuel    Canada
Terry      China
Name: Country, dtype: str

In [43]:
df2.loc[:, ['Country', 'Course']]

        Country            Course
Student
David        UK            Python
Samuel   Canada   Data Structures
Terry     China  Machine Learning
Evan        USA   Web Development

In [44]:
df2.loc['Samuel' : 'Evan', 'Contry':'Marks']

        Country            Course  Marks
Student
Samuel   Canada   Data Structures     72
Terry     China  Machine Learning     89
Evan        USA   Web Development     76