In [18]:
import requests
import json
import pandas as pd

#### We will obtain the fruityvice API data using requests.get("url") function. The data is in a json format.

In [13]:
data = requests.get("https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all")
data

In [14]:
data.text

'[{"name":"Persimmon","id":52,"family":"Ebenaceae","order":"Rosales","genus":"Diospyros","nutritions":{"calories":81,"fat":0.0,"sugar":18.0,"carbohydrates":18.0,"protein":0.0}},{"name":"Strawberry","id":3,"family":"Rosaceae","order":"Rosales","genus":"Fragaria","nutritions":{"calories":29,"fat":0.4,"sugar":5.4,"carbohydrates":5.5,"protein":0.8}},{"name":"Banana","id":1,"family":"Musaceae","order":"Zingiberales","genus":"Musa","nutritions":{"calories":96,"fat":0.2,"sugar":17.2,"carbohydrates":22.0,"protein":1.0}},{"name":"Tomato","id":5,"family":"Solanaceae","order":"Solanales","genus":"Solanum","nutritions":{"calories":74,"fat":0.2,"sugar":2.6,"carbohydrates":3.9,"protein":0.9}},{"name":"Pear","id":4,"family":"Rosaceae","order":"Rosales","genus":"Pyrus","nutritions":{"calories":57,"fat":0.1,"sugar":10.0,"carbohydrates":15.0,"protein":0.4}},{"name":"Durian","id":60,"family":"Malvaceae","order":"Malvales","genus":"Durio","nutritions":{"calories":147,"fat":5.3,"sugar":6.75,"carbohydrates":27.1,"protein":1.5}},{"name":"Blackberry","id":64,"family":"Rosaceae","order":"Rosales","genus":"Rubus","nutritions":{"calories":40,"fat":0.4,"sugar":4.5,"carbohydrates":9.0,"protein":1.3}},{"name":"Lingonberry","id":65,"family":"Ericaceae","order":"Ericales","genus":"Vaccinium","nutritions":{"calories":50,"fat":0.34,"sugar":5.74,"carbohydrates":11.3,"protein":0.75}},{"name":"Kiwi","id":66,"family":"Actinidiaceae","order":"Struthioniformes","genus":"Apteryx","nutritions":{"calories":61,"fat":0.5,"sugar":9.0,"carbohydrates":15.0,"protein":1.1}},{"name":"Lychee","id":67,"family":"Sapindaceae","order":"Sapindales","genus":"Litchi","nutritions":{"calories":66,"fat":0.44,"sugar":15.0,"carbohydrates":17.0,"protein":0.8}},{"name":"Pineapple","id":10,"family":"Bromeliaceae","order":"Poales","genus":"Ananas","nutritions":{"calories":50,"fat":0.12,"sugar":9.85,"carbohydrates":13.12,"protein":0.54}},{"name":"Fig","id":68,"family":"Moraceae","order":"Rosales","genus":"Ficus","nutritions":{"calories":74,"fat":0.3,"sugar":16.0,"carbohydrates":19.0,"protein":0.8}},{"name":"Gooseberry","id":69,"family":"Grossulariaceae","order":"Saxifragales","genus":"Ribes","nutritions":{"calories":44,"fat":0.6,"sugar":0.0,"carbohydrates":10.0,"protein":0.9}},{"name":"Passionfruit","id":70,"family":"Passifloraceae","order":"Malpighiales","genus":"Passiflora","nutritions":{"calories":97,"fat":0.7,"sugar":11.2,"carbohydrates":22.4,"protein":2.2}},{"name":"Plum","id":71,"family":"Rosaceae","order":"Rosales","genus":"Prunus","nutritions":{"calories":46,"fat":0.28,"sugar":9.92,"carbohydrates":11.4,"protein":0.7}},{"name":"Orange","id":2,"family":"Rutaceae","order":"Sapindales","genus":"Citrus","nutritions":{"calories":43,"fat":0.2,"sugar":8.2,"carbohydrates":8.3,"protein":1.0}},{"name":"GreenApple","id":72,"family":"Rosaceae","order":"Rosales","genus":"Malus","nutritions":{"calories":21,"fat":0.1,"sugar":6.4,"carbohydrates":3.1,"protein":0.4}},{"name":"Raspberry","id":23,"family":"Rosaceae","order":"Rosales","genus":"Rubus","nutritions":{"calories":53,"fat":0.7,"sugar":4.4,"carbohydrates":12.0,"protein":1.2}},{"name":"Watermelon","id":25,"family":"Cucurbitaceae","order":"Cucurbitales","genus":"Citrullus","nutritions":{"calories":30,"fat":0.2,"sugar":6.0,"carbohydrates":8.0,"protein":0.6}},{"name":"Lemon","id":26,"family":"Rutaceae","order":"Sapindales","genus":"Citrus","nutritions":{"calories":29,"fat":0.3,"sugar":2.5,"carbohydrates":9.0,"protein":1.1}},{"name":"Mango","id":27,"family":"Anacardiaceae","order":"Sapindales","genus":"Mangifera","nutritions":{"calories":60,"fat":0.38,"sugar":13.7,"carbohydrates":15.0,"protein":0.82}},{"name":"Blueberry","id":33,"family":"Rosaceae","order":"Rosales","genus":"Fragaria","nutritions":{"calories":29,"fat":0.4,"sugar":5.4,"carbohydrates":5.5,"protein":0.0}},{"name":"Apple","id":6,"family":"Rosaceae","order":"Rosales","genus":"Malus","nutritions":{"calories":52,"fat":0.4,"sugar":10.3,"carbohydrates":11.4,"protein":0.3}},{"name":"Guava","id":37,"family":"Myrtaceae","order":"Myrtales","genus":"Psidium","nutritions":{"calories":68,"fat":1.0,"sugar":9.0,"carbohydrates":14.0,"protein":2.6}},{"name":"Apricot","id":35,"family":"Rosaceae","order":"Rosales","genus":"Prunus","nutritions":{"calories":15,"fat":0.1,"sugar":3.2,"carbohydrates":3.9,"protein":0.5}},{"name":"Melon","id":41,"family":"Cucurbitaceae","order":"Cucurbitaceae","genus":"Cucumis","nutritions":{"calories":34,"fat":0.0,"sugar":8.0,"carbohydrates":8.0,"protein":0.0}},{"name":"Tangerine","id":77,"family":"Rutaceae","order":"Sapindales","genus":"Citrus","nutritions":{"calories":45,"fat":0.4,"sugar":9.1,"carbohydrates":8.3,"protein":0.0}},{"name":"Pitahaya","id":78,"family":"Cactaceae","order":"Caryophyllales","genus":"Cactaceae","nutritions":{"calories":36,"fat":0.4,"sugar":3.0,"carbohydrates":7.0,"protein":1.0}},{"name":"Lime","id":44,"family":"Rutaceae","order":"Sapindales","genus":"Citrus","nutritions":{"calories":25,"fat":0.1,"sugar":1.7,"carbohydrates":8.4,"protein":0.3}},{"name":"Pomegranate","id":79,"family":"Lythraceae","order":"Myrtales","genus":"Punica","nutritions":{"calories":83,"fat":1.2,"sugar":13.7,"carbohydrates":18.7,"protein":1.7}},{"name":"Dragonfruit","id":80,"family":"Cactaceae","order":"Caryophyllales","genus":"Selenicereus","nutritions":{"calories":60,"fat":1.5,"sugar":8.0,"carbohydrates":9.0,"protein":9.0}},{"name":"Grape","id":81,"family":"Vitaceae","order":"Vitales","genus":"Vitis","nutritions":{"calories":69,"fat":0.16,"sugar":16.0,"carbohydrates":18.1,"protein":0.72}},{"name":"Morus","id":82,"family":"Moraceae","order":"Rosales","genus":"Morus","nutritions":{"calories":43,"fat":0.39,"sugar":8.1,"carbohydrates":9.8,"protein":1.44}},{"name":"Feijoa","id":76,"family":"Myrtaceae","order":"Myrtoideae","genus":"Sellowiana","nutritions":{"calories":44,"fat":0.4,"sugar":3.0,"carbohydrates":8.0,"protein":0.6}},{"name":"Avocado","id":84,"family":"Lauraceae","order":"Laurales","genus":"Persea","nutritions":{"calories":160,"fat":14.66,"sugar":0.66,"carbohydrates":8.53,"protein":2.0}},{"name":"Kiwifruit","id":85,"family":"Actinidiaceae","order":"Ericales","genus":"Actinidia","nutritions":{"calories":61,"fat":0.5,"sugar":8.9,"carbohydrates":14.6,"protein":1.14}},{"name":"Cranberry","id":87,"family":"Ericaceae","order":"Ericales","genus":"Vaccinium","nutritions":{"calories":46,"fat":0.1,"sugar":4.0,"carbohydrates":12.2,"protein":0.4}},{"name":"Cherry","id":9,"family":"Rosaceae","order":"Rosales","genus":"Prunus","nutritions":{"calories":50,"fat":0.3,"sugar":8.0,"carbohydrates":12.0,"protein":1.0}},{"name":"Peach","id":86,"family":"Rosaceae","order":"Rosales","genus":"Prunus","nutritions":{"calories":39,"fat":0.25,"sugar":8.4,"carbohydrates":9.5,"protein":0.9}},{"name":"Jackfruit","id":94,"family":"Moraceae","order":"Rosales","genus":"Artocarpus","nutritions":{"calories":95,"fat":0.0,"sugar":19.1,"carbohydrates":23.2,"protein":1.72}},{"name":"Horned Melon","id":95,"family":"Cucurbitaceae","order":"Cucurbitales","genus":"Cucumis","nutritions":{"calories":44,"fat":1.26,"sugar":0.5,"carbohydrates":7.56,"protein":1.78}},{"name":"Hazelnut","id":96,"family":"Betulaceae","order":"Fagales","genus":"Corylus","nutritions":{"calories":628,"fat":61.0,"sugar":4.3,"carbohydrates":17.0,"protein":15.0}},{"name":"Pomelo","id":98,"family":"Rutaceae","order":"Sapindales","genus":"Citrus","nutritions":{"calories":37,"fat":0.0,"sugar":8.5,"carbohydrates":9.67,"protein":0.82}},{"name":"Mangosteen","id":99,"family":"Clusiaceae","order":"Malpighiales","genus":"Garcinia","nutritions":{"calories":73,"fat":0.58,"sugar":16.11,"carbohydrates":17.91,"protein":0.41}},{"name":"Pumpkin","id":100,"family":"Cucurbitaceae","order":"Cucurbitales","genus":"Cucurbita","nutritions":{"calories":25,"fat":0.3,"sugar":3.3,"carbohydrates":4.6,"protein":1.1}},{"name":"Japanese Persimmon","id":101,"family":" Ebenaceae","order":" Ericales","genus":"Diospyros","nutritions":{"calories":70,"fat":0.2,"sugar":13.0,"carbohydrates":19.0,"protein":0.6}},{"name":"Papaya","id":42,"family":"Caricaceae","order":"Brassicales","genus":"Carica","nutritions":{"calories":39,"fat":0.3,"sugar":4.4,"carbohydrates":5.8,"protein":0.5}},{"name":"Annona","id":103,"family":"Annonaceae","order":"Rosales","genus":"Annonas","nutritions":{"calories":92,"fat":0.29,"sugar":3.4,"carbohydrates":19.1,"protein":1.5}},{"name":"Ceylon Gooseberry","id":104,"family":"Salicaceae","order":"Malpighiales","genus":"Dovyalis","nutritions":{"calories":47,"fat":0.3,"sugar":8.1,"carbohydrates":9.6,"protein":1.2}}]'

In [17]:
results = json.loads(data.text)
results

[{'name': 'Persimmon',
  'id': 52,
  'family': 'Ebenaceae',
  'order': 'Rosales',
  'genus': 'Diospyros',
  'nutritions': {'calories': 81,
   'fat': 0.0,
   'sugar': 18.0,
   'carbohydrates': 18.0,
   'protein': 0.0}},
 {'name': 'Strawberry',
  'id': 3,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Fragaria',
  'nutritions': {'calories': 29,
   'fat': 0.4,
   'sugar': 5.4,
   'carbohydrates': 5.5,
   'protein': 0.8}},
 {'name': 'Banana',
  'id': 1,
  'family': 'Musaceae',
  'order': 'Zingiberales',
  'genus': 'Musa',
  'nutritions': {'calories': 96,
   'fat': 0.2,
   'sugar': 17.2,
   'carbohydrates': 22.0,
   'protein': 1.0}},
 {'name': 'Tomato',
  'id': 5,
  'family': 'Solanaceae',
  'order': 'Solanales',
  'genus': 'Solanum',
  'nutritions': {'calories': 74,
   'fat': 0.2,
   'sugar': 2.6,
   'carbohydrates': 3.9,
   'protein': 0.9}},
 {'name': 'Pear',
  'id': 4,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Pyrus',
  'nutritions': {'calories': 57,
   'fat': 0.1,
   'sugar': 10.0,
   'carbohydrates': 15.0,
   'protein': 0.4}},
 {'name': 'Durian',
  'id': 60,
  'family': 'Malvaceae',
  'order': 'Malvales',
  'genus': 'Durio',
  'nutritions': {'calories': 147,
   'fat': 5.3,
   'sugar': 6.75,
   'carbohydrates': 27.1,
   'protein': 1.5}},
 {'name': 'Blackberry',
  'id': 64,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Rubus',
  'nutritions': {'calories': 40,
   'fat': 0.4,
   'sugar': 4.5,
   'carbohydrates': 9.0,
   'protein': 1.3}},
 {'name': 'Lingonberry',
  'id': 65,
  'family': 'Ericaceae',
  'order': 'Ericales',
  'genus': 'Vaccinium',
  'nutritions': {'calories': 50,
   'fat': 0.34,
   'sugar': 5.74,
   'carbohydrates': 11.3,
   'protein': 0.75}},
 {'name': 'Kiwi',
  'id': 66,
  'family': 'Actinidiaceae',
  'order': 'Struthioniformes',
  'genus': 'Apteryx',
  'nutritions': {'calories': 61,
   'fat': 0.5,
   'sugar': 9.0,
   'carbohydrates': 15.0,
   'protein': 1.1}},
 {'name': 'Lychee',
  'id': 67,
  'family': 'Sapindaceae',
  'order': 'Sapindales',
  'genus': 'Litchi',
  'nutritions': {'calories': 66,
   'fat': 0.44,
   'sugar': 15.0,
   'carbohydrates': 17.0,
   'protein': 0.8}},
 {'name': 'Pineapple',
  'id': 10,
  'family': 'Bromeliaceae',
  'order': 'Poales',
  'genus': 'Ananas',
  'nutritions': {'calories': 50,
   'fat': 0.12,
   'sugar': 9.85,
   'carbohydrates': 13.12,
   'protein': 0.54}},
 {'name': 'Fig',
  'id': 68,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Ficus',
  'nutritions': {'calories': 74,
   'fat': 0.3,
   'sugar': 16.0,
   'carbohydrates': 19.0,
   'protein': 0.8}},
 {'name': 'Gooseberry',
  'id': 69,
  'family': 'Grossulariaceae',
  'order': 'Saxifragales',
  'genus': 'Ribes',
  'nutritions': {'calories': 44,
   'fat': 0.6,
   'sugar': 0.0,
   'carbohydrates': 10.0,
   'protein': 0.9}},
 {'name': 'Passionfruit',
  'id': 70,
  'family': 'Passifloraceae',
  'order': 'Malpighiales',
  'genus': 'Passiflora',
  'nutritions': {'calories': 97,
   'fat': 0.7,
   'sugar': 11.2,
   'carbohydrates': 22.4,
   'protein': 2.2}},
 {'name': 'Plum',
  'id': 71,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 46,
   'fat': 0.28,
   'sugar': 9.92,
   'carbohydrates': 11.4,
   'protein': 0.7}},
 {'name': 'Orange',
  'id': 2,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 43,
   'fat': 0.2,
   'sugar': 8.2,
   'carbohydrates': 8.3,
   'protein': 1.0}},
 {'name': 'GreenApple',
  'id': 72,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Malus',
  'nutritions': {'calories': 21,
   'fat': 0.1,
   'sugar': 6.4,
   'carbohydrates': 3.1,
   'protein': 0.4}},
 {'name': 'Raspberry',
  'id': 23,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Rubus',
  'nutritions': {'calories': 53,
   'fat': 0.7,
   'sugar': 4.4,
   'carbohydrates': 12.0,
   'protein': 1.2}},
 {'name': 'Watermelon',
  'id': 25,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Citrullus',
  'nutritions': {'calories': 30,
   'fat': 0.2,
   'sugar': 6.0,
   'carbohydrates': 8.0,
   'protein': 0.6}},
 {'name': 'Lemon',
  'id': 26,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 29,
   'fat': 0.3,
   'sugar': 2.5,
   'carbohydrates': 9.0,
   'protein': 1.1}},
 {'name': 'Mango',
  'id': 27,
  'family': 'Anacardiaceae',
  'order': 'Sapindales',
  'genus': 'Mangifera',
  'nutritions': {'calories': 60,
   'fat': 0.38,
   'sugar': 13.7,
   'carbohydrates': 15.0,
   'protein': 0.82}},
 {'name': 'Blueberry',
  'id': 33,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Fragaria',
  'nutritions': {'calories': 29,
   'fat': 0.4,
   'sugar': 5.4,
   'carbohydrates': 5.5,
   'protein': 0.0}},
 {'name': 'Apple',
  'id': 6,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Malus',
  'nutritions': {'calories': 52,
   'fat': 0.4,
   'sugar': 10.3,
   'carbohydrates': 11.4,
   'protein': 0.3}},
 {'name': 'Guava',
  'id': 37,
  'family': 'Myrtaceae',
  'order': 'Myrtales',
  'genus': 'Psidium',
  'nutritions': {'calories': 68,
   'fat': 1.0,
   'sugar': 9.0,
   'carbohydrates': 14.0,
   'protein': 2.6}},
 {'name': 'Apricot',
  'id': 35,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 15,
   'fat': 0.1,
   'sugar': 3.2,
   'carbohydrates': 3.9,
   'protein': 0.5}},
 {'name': 'Melon',
  'id': 41,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitaceae',
  'genus': 'Cucumis',
  'nutritions': {'calories': 34,
   'fat': 0.0,
   'sugar': 8.0,
   'carbohydrates': 8.0,
   'protein': 0.0}},
 {'name': 'Tangerine',
  'id': 77,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 45,
   'fat': 0.4,
   'sugar': 9.1,
   'carbohydrates': 8.3,
   'protein': 0.0}},
 {'name': 'Pitahaya',
  'id': 78,
  'family': 'Cactaceae',
  'order': 'Caryophyllales',
  'genus': 'Cactaceae',
  'nutritions': {'calories': 36,
   'fat': 0.4,
   'sugar': 3.0,
   'carbohydrates': 7.0,
   'protein': 1.0}},
 {'name': 'Lime',
  'id': 44,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 25,
   'fat': 0.1,
   'sugar': 1.7,
   'carbohydrates': 8.4,
   'protein': 0.3}},
 {'name': 'Pomegranate',
  'id': 79,
  'family': 'Lythraceae',
  'order': 'Myrtales',
  'genus': 'Punica',
  'nutritions': {'calories': 83,
   'fat': 1.2,
   'sugar': 13.7,
   'carbohydrates': 18.7,
   'protein': 1.7}},
 {'name': 'Dragonfruit',
  'id': 80,
  'family': 'Cactaceae',
  'order': 'Caryophyllales',
  'genus': 'Selenicereus',
  'nutritions': {'calories': 60,
   'fat': 1.5,
   'sugar': 8.0,
   'carbohydrates': 9.0,
   'protein': 9.0}},
 {'name': 'Grape',
  'id': 81,
  'family': 'Vitaceae',
  'order': 'Vitales',
  'genus': 'Vitis',
  'nutritions': {'calories': 69,
   'fat': 0.16,
   'sugar': 16.0,
   'carbohydrates': 18.1,
   'protein': 0.72}},
 {'name': 'Morus',
  'id': 82,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Morus',
  'nutritions': {'calories': 43,
   'fat': 0.39,
   'sugar': 8.1,
   'carbohydrates': 9.8,
   'protein': 1.44}},
 {'name': 'Feijoa',
  'id': 76,
  'family': 'Myrtaceae',
  'order': 'Myrtoideae',
  'genus': 'Sellowiana',
  'nutritions': {'calories': 44,
   'fat': 0.4,
   'sugar': 3.0,
   'carbohydrates': 8.0,
   'protein': 0.6}},
 {'name': 'Avocado',
  'id': 84,
  'family': 'Lauraceae',
  'order': 'Laurales',
  'genus': 'Persea',
  'nutritions': {'calories': 160,
   'fat': 14.66,
   'sugar': 0.66,
   'carbohydrates': 8.53,
   'protein': 2.0}},
 {'name': 'Kiwifruit',
  'id': 85,
  'family': 'Actinidiaceae',
  'order': 'Ericales',
  'genus': 'Actinidia',
  'nutritions': {'calories': 61,
   'fat': 0.5,
   'sugar': 8.9,
   'carbohydrates': 14.6,
   'protein': 1.14}},
 {'name': 'Cranberry',
  'id': 87,
  'family': 'Ericaceae',
  'order': 'Ericales',
  'genus': 'Vaccinium',
  'nutritions': {'calories': 46,
   'fat': 0.1,
   'sugar': 4.0,
   'carbohydrates': 12.2,
   'protein': 0.4}},
 {'name': 'Cherry',
  'id': 9,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 50,
   'fat': 0.3,
   'sugar': 8.0,
   'carbohydrates': 12.0,
   'protein': 1.0}},
 {'name': 'Peach',
  'id': 86,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'genus': 'Prunus',
  'nutritions': {'calories': 39,
   'fat': 0.25,
   'sugar': 8.4,
   'carbohydrates': 9.5,
   'protein': 0.9}},
 {'name': 'Jackfruit',
  'id': 94,
  'family': 'Moraceae',
  'order': 'Rosales',
  'genus': 'Artocarpus',
  'nutritions': {'calories': 95,
   'fat': 0.0,
   'sugar': 19.1,
   'carbohydrates': 23.2,
   'protein': 1.72}},
 {'name': 'Horned Melon',
  'id': 95,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Cucumis',
  'nutritions': {'calories': 44,
   'fat': 1.26,
   'sugar': 0.5,
   'carbohydrates': 7.56,
   'protein': 1.78}},
 {'name': 'Hazelnut',
  'id': 96,
  'family': 'Betulaceae',
  'order': 'Fagales',
  'genus': 'Corylus',
  'nutritions': {'calories': 628,
   'fat': 61.0,
   'sugar': 4.3,
   'carbohydrates': 17.0,
   'protein': 15.0}},
 {'name': 'Pomelo',
  'id': 98,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'genus': 'Citrus',
  'nutritions': {'calories': 37,
   'fat': 0.0,
   'sugar': 8.5,
   'carbohydrates': 9.67,
   'protein': 0.82}},
 {'name': 'Mangosteen',
  'id': 99,
  'family': 'Clusiaceae',
  'order': 'Malpighiales',
  'genus': 'Garcinia',
  'nutritions': {'calories': 73,
   'fat': 0.58,
   'sugar': 16.11,
   'carbohydrates': 17.91,
   'protein': 0.41}},
 {'name': 'Pumpkin',
  'id': 100,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'genus': 'Cucurbita',
  'nutritions': {'calories': 25,
   'fat': 0.3,
   'sugar': 3.3,
   'carbohydrates': 4.6,
   'protein': 1.1}},
 {'name': 'Japanese Persimmon',
  'id': 101,
  'family': ' Ebenaceae',
  'order': ' Ericales',
  'genus': 'Diospyros',
  'nutritions': {'calories': 70,
   'fat': 0.2,
   'sugar': 13.0,
   'carbohydrates': 19.0,
   'protein': 0.6}},
 {'name': 'Papaya',
  'id': 42,
  'family': 'Caricaceae',
  'order': 'Brassicales',
  'genus': 'Carica',
  'nutritions': {'calories': 39,
   'fat': 0.3,
   'sugar': 4.4,
   'carbohydrates': 5.8,
   'protein': 0.5}},
 {'name': 'Annona',
  'id': 103,
  'family': 'Annonaceae',
  'order': 'Rosales',
  'genus': 'Annonas',
  'nutritions': {'calories': 92,
   'fat': 0.29,
   'sugar': 3.4,
   'carbohydrates': 19.1,
   'protein': 1.5}},
 {'name': 'Ceylon Gooseberry',
  'id': 104,
  'family': 'Salicaceae',
  'order': 'Malpighiales',
  'genus': 'Dovyalis',
  'nutritions': {'calories': 47,
   'fat': 0.3,
   'sugar': 8.1,
   'carbohydrates': 9.6,
   'protein': 1.2}}]

In [20]:
pd.DataFrame(results)

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."
10,Pineapple,10,Bromeliaceae,Poales,Ananas,"{'calories': 50, 'fat': 0.12, 'sugar': 9.85, '..."
11,Fig,68,Moraceae,Rosales,Ficus,"{'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c..."
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,"{'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca..."
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,"{'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c..."
14,Plum,71,Rosaceae,Rosales,Prunus,"{'calories': 46, 'fat': 0.28, 'sugar': 9.92, '..."
15,Orange,2,Rutaceae,Sapindales,Citrus,"{'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca..."
16,GreenApple,72,Rosaceae,Rosales,Malus,"{'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca..."
17,Raspberry,23,Rosaceae,Rosales,Rubus,"{'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca..."
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,"{'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca..."
19,Lemon,26,Rutaceae,Sapindales,Citrus,"{'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca..."
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,"{'calories': 60, 'fat': 0.38, 'sugar': 13.7, '..."
21,Blueberry,33,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
22,Apple,6,Rosaceae,Rosales,Malus,"{'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c..."
23,Guava,37,Myrtaceae,Myrtales,Psidium,"{'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca..."
24,Apricot,35,Rosaceae,Rosales,Prunus,"{'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca..."
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,"{'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca..."
26,Tangerine,77,Rutaceae,Sapindales,Citrus,"{'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca..."
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,"{'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca..."
28,Lime,44,Rutaceae,Sapindales,Citrus,"{'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca..."
29,Pomegranate,79,Lythraceae,Myrtales,Punica,"{'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c..."
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,"{'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca..."
31,Grape,81,Vitaceae,Vitales,Vitis,"{'calories': 69, 'fat': 0.16, 'sugar': 16.0, '..."
32,Morus,82,Moraceae,Rosales,Morus,"{'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c..."
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,"{'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca..."
34,Avocado,84,Lauraceae,Laurales,Persea,"{'calories': 160, 'fat': 14.66, 'sugar': 0.66,..."
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,"{'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca..."
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,"{'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca..."
37,Cherry,9,Rosaceae,Rosales,Prunus,"{'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca..."
38,Peach,86,Rosaceae,Rosales,Prunus,"{'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c..."
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,"{'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c..."
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,"{'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c..."
41,Hazelnut,96,Betulaceae,Fagales,Corylus,"{'calories': 628, 'fat': 61.0, 'sugar': 4.3, '..."
42,Pomelo,98,Rutaceae,Sapindales,Citrus,"{'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'ca..."
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,"{'calories': 73, 'fat': 0.58, 'sugar': 16.11, ..."
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,"{'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'ca..."
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,"{'calories': 70, 'fat': 0.2, 'sugar': 13.0, 'c..."
46,Papaya,42,Caricaceae,Brassicales,Carica,"{'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'ca..."
47,Annona,103,Annonaceae,Rosales,Annonas,"{'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'c..."
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,"{'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'ca..."

#### The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.

In [24]:
df2 = pd.json_normalize(results)
df2.head(3)

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.0,18.0,18.0,0.0
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.4,5.4,5.5,0.8
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.2,17.2,22.0,1.0

In [37]:
df2[df2['name']=='Banana']

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.2,17.2,22.0,1.0

In [41]:
df2[df2['name'] == 'Cherry']

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.3,8.0,12.0,1.0

In [43]:
df2.loc[df2['name'] == 'Cherry']

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.3,8.0,12.0,1.0

In [56]:
df3 = df2[df2['name'] == 'Cherry']
df3.loc[:,['name', 'family', 'genus']]

      name    family   genus
37  Cherry  Rosaceae  Prunus