In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

file_path= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/laptop_pricing_dataset_mod1.csv"

In [52]:
df = pd.read_csv(file_path, header=0)
df.head(2)

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,0,Acer,4,IPS Panel,2,1,5,35.560,1.6,8,256,1.6,978
1,1,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.2,634

In [53]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      238 non-null    int64
 1   Manufacturer    238 non-null    str
 2   Category        238 non-null    int64
 3   Screen          238 non-null    str
 4   GPU             238 non-null    int64
 5   OS              238 non-null    int64
 6   CPU_core        238 non-null    int64
 7   Screen_Size_cm  234 non-null    float64
 8   CPU_frequency   238 non-null    float64
 9   RAM_GB          238 non-null    int64
 10  Storage_GB_SSD  238 non-null    int64
 11  Weight_kg       233 non-null    float64
 12  Price           238 non-null    int64
dtypes: float64(3), int64(8), str(2)
memory usage: 24.3 KB
None

In [54]:
df["Screen_Size_cm"] = np.round(df["Screen_Size_cm"], 2)
df.head(3)

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,0,Acer,4,IPS Panel,2,1,5,35.56,1.6,8,256,1.6,978
1,1,Dell,3,Full HD,1,1,3,39.62,2.0,4,256,2.2,634
2,2,Dell,3,Full HD,1,1,7,39.62,2.7,8,256,2.2,946

In [55]:
missing_data = df.isnull()
missing_data.head(5)

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False

In [56]:
list(missing_data.columns)

['Unnamed: 0',
 'Manufacturer',
 'Category',
 'Screen',
 'GPU',
 'OS',
 'CPU_core',
 'Screen_Size_cm',
 'CPU_frequency',
 'RAM_GB',
 'Storage_GB_SSD',
 'Weight_kg',
 'Price']

In [57]:
for column in list(missing_data.columns):
    print(f"Column: {missing_data[column].value_counts()}  \n")

Column: Unnamed: 0
False    238
Name: count, dtype: int64

Column: Manufacturer
False    238
Name: count, dtype: int64

Column: Category
False    238
Name: count, dtype: int64

Column: Screen
False    238
Name: count, dtype: int64

Column: GPU
False    238
Name: count, dtype: int64

Column: OS
False    238
Name: count, dtype: int64

Column: CPU_core
False    238
Name: count, dtype: int64

Column: Screen_Size_cm
False    234
True       4
Name: count, dtype: int64

Column: CPU_frequency
False    238
Name: count, dtype: int64

Column: RAM_GB
False    238
Name: count, dtype: int64

Column: Storage_GB_SSD
False    238
Name: count, dtype: int64

Column: Weight_kg
False    233
True       5
Name: count, dtype: int64

Column: Price
False    238
Name: count, dtype: int64

In [58]:
avg_weight = np.mean(df["Weight_kg"].astype('float'))
avg_weight

np.float64(1.8622317596566522)

In [59]:
df["Weight_kg"]= df['Weight_kg'].replace(np.nan, avg_weight)
df.head(3)

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,0,Acer,4,IPS Panel,2,1,5,35.56,1.6,8,256,1.6,978
1,1,Dell,3,Full HD,1,1,3,39.62,2.0,4,256,2.2,634
2,2,Dell,3,Full HD,1,1,7,39.62,2.7,8,256,2.2,946

In [60]:
common_screen_size = df['Screen_Size_cm'].value_counts().idxmax()
common_screen_size

np.float64(39.62)

In [61]:
df["Screen_Size_cm"] = df["Screen_Size_cm"].replace(np.nan, common_screen_size)
df.head(5)

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,0,Acer,4,IPS Panel,2,1,5,35.56,1.6,8,256,1.60,978
1,1,Dell,3,Full HD,1,1,3,39.62,2.0,4,256,2.20,634
2,2,Dell,3,Full HD,1,1,7,39.62,2.7,8,256,2.20,946
3,3,Dell,4,IPS Panel,2,1,5,33.78,1.6,8,128,1.22,1244
4,4,HP,4,Full HD,2,1,7,39.62,1.8,8,256,1.91,837

Both "Weight_kg" and "Screen_Size_cm" are seen to have the data type "Object", while both of them should be having a data type of "float". Write a code to fix the data type of these two columns.

In [62]:
df[['Weight_kg', 'Screen_Size_cm']] = df[['Weight_kg', 'Screen_Size_cm']].astype(float)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      238 non-null    int64
 1   Manufacturer    238 non-null    str
 2   Category        238 non-null    int64
 3   Screen          238 non-null    str
 4   GPU             238 non-null    int64
 5   OS              238 non-null    int64
 6   CPU_core        238 non-null    int64
 7   Screen_Size_cm  238 non-null    float64
 8   CPU_frequency   238 non-null    float64
 9   RAM_GB          238 non-null    int64
 10  Storage_GB_SSD  238 non-null    int64
 11  Weight_kg       238 non-null    float64
 12  Price           238 non-null    int64
dtypes: float64(3), int64(8), str(2)
memory usage: 24.3 KB

Data Standardization¶
The value of Screen_size usually has a standard unit of inches. Similarly, weight of the laptop is needed to be in pounds. Use the below mentioned units of conversion and write a code to modify the columns of the dataframe accordingly. Update their names as well.

1 inch = 2.54 cm
1 kg   = 2.205 pounds

In [63]:
df["Screen_Size_cm"] = df["Screen_Size_cm"]/2.54
df.rename(columns={"Screen_Size_cm": "Screen_Size_inch"}, inplace=True)

In [64]:
df.head(3)

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,0,Acer,4,IPS Panel,2,1,5,14.000000,1.6,8,256,1.6,978
1,1,Dell,3,Full HD,1,1,3,15.598425,2.0,4,256,2.2,634
2,2,Dell,3,Full HD,1,1,7,15.598425,2.7,8,256,2.2,946

In [65]:
df["Weight_kg"] = df["Weight_kg"]*2.205
df.rename(columns={"Weight_kg": "Weight_pounds"}, inplace=True)
df.head(5)

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price
0,0,Acer,4,IPS Panel,2,1,5,14.000000,1.6,8,256,3.52800,978
1,1,Dell,3,Full HD,1,1,3,15.598425,2.0,4,256,4.85100,634
2,2,Dell,3,Full HD,1,1,7,15.598425,2.7,8,256,4.85100,946
3,3,Dell,4,IPS Panel,2,1,5,13.299213,1.6,8,128,2.69010,1244
4,4,HP,4,Full HD,2,1,7,15.598425,1.8,8,256,4.21155,837